name: CI
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run lint:report
      - uses: actions/upload-artifact@v3
        with:
          name: reports
          path: reports
          retention-days: 5
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run test:report
      - uses: actions/upload-artifact@v3
        with:
          name: reports
          path: reports
          retention-days: 5
